version: '3'
services:
  bp-vue:
    build: ./vue
    ports:
      - 24440:8080
    container_name: bp-vue
    hostname: bp-vue
    working_dir: /src
    volumes:
      - ../src/vue:/src
    tty: true
    environment:
      - VUE_APP_API_ENDPOINT=http://localhost:24441/

  bp-api:
    build: ./api
    ports:
      - 24441:8081
    container_name: bp-api
    hostname: bp-api
    working_dir: /src
    volumes:
      - ../src/api:/src
    tty: true